MONGODB_HOST: mongodb-{{ env }}.malleswari.fun
REDIS_HOST: redis-{{ env }}.malleswari.fun
CATALOGUE_HOST: catalogue-{{ env }}.malleswari.fun
MYSQL_HOST: mysql-{{ env }}.malleswari.fun
CART_HOST: cart-{{ env }}.malleswari.fun
USER_HOST: user-{{ env }}.malleswari.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.malleswari.fun
SHIPPING_HOST: shipping-{{ env }}.malleswari.fun
PAYMENT_HOST: payment-{{ env }}.malleswari.fun