MONGODB_HOST: mongodb-{{ env }}.malleswari.fun
REDIS_HOST: redis-{{ env }}.malleswari.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.malleswari.fun
MYSQL_HOST: mysql-{{ env }}.malleswari.fun
CART_HOST: cart.backend-alb-{{ env }}.malleswari.fun
USER_HOST: user.backend-alb-{{ env }}.malleswari.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.malleswari.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.malleswari.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.malleswari.fun