MONGODB_HOST: mongodb.malleswari.fun
REDIS_HOST: redis.malleswari.fun
CATALOGUE_HOST: catalogue.malleswari.fun
MYSQL_HOST: mysql.malleswari.fun
CART_HOST: cart.malleswari.fun
USER_HOST: user.malleswari.fun
RABBITMQ_HOST: rabbitmq.malleswari.fun
SHIPPING_HOST: shipping.malleswari.fun
PAYMENT_HOST: payment.malleswari.fun